### ISSUE TITLE
Reset game

### ISSUE THREAD

**Issue by perennialAutodidact** [perennialAutodidact/memory-snap#78]
**Issue #77** should be completed before starting this issue

After the game is won and the "game over" message is displayed as per [issue #77](https://github.com/perennialAutodidact/memory-snap/issues/77), the user should have the option to reset the game. 

I'll draw up designs for what the game over page should look like.

When the game is reset, all appropriate context values should be reset to their defaults. The `tiles` array does not need to be created again, but it should be shuffled so the game is different the next time around. Eventually, the user will have the option to change the photos and other settings that they will configure in the setup form.

**Comment by russfraze** [comment]
@perennialAutodidact I'm wondering if we should have two separate buttons so that once could be reset game and the other play again. 

Reset game would reset all the values and take you back to the setup form so you can enter two new player names. Play again would keep the names and take you back to the form step where you choose what kind of images you want. 

Or maybe its just reset game but it still keeps the player names and just asks for a new image search term and number of tiles. 

Play again could also just start over the exact same game but with the order of the tiles changed. Which way makes the most sense to you?

**Comment by perennialAutodidact** [comment]
I was thinking we'd have a settings menu that would give the users the ability to start the current game over and also the ability to return to the setup menu to adjust the game options. 

What if on the game over screen we had a button to reset the game with the same settings "Play again" and a link to return to the "Setup menu"?
